name: Check Solutions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Run Solutions
      working-directory: ./October 2021
      run: for sol in *.py; do python3 "$sol"; done;
